In [6]:
print "Hello World"

Hello World

In [8]:
import csv
import pandas
data = pandas.read_csv("NYPD_Complaint_Data_Historic.csv", usecols=[1,2,7,13,21,22])
data

,CMPLNT_FR_DT,CMPLNT_FR_TM,OFNS_DESC,BORO_NM,Latitude,Longitude
0,12/31/2015,23:45:00,FORGERY,BRONX,40.828848,-73.916661
1,12/31/2015,23:36:00,MURDER & NON-NEGL. MANSLAUGHTER,QUEENS,40.697338,-73.784557
2,12/31/2015,23:30:00,DANGEROUS DRUGS,MANHATTAN,40.802607,-73.945052
3,12/31/2015,23:30:00,ASSAULT 3 & RELATED OFFENSES,QUEENS,40.654549,-73.726339
4,12/31/2015,23:25:00,ASSAULT 3 & RELATED OFFENSES,MANHATTAN,40.738002,-73.987891
5,12/31/2015,23:18:00,FELONY ASSAULT,BROOKLYN,40.665023,-73.957111
6,12/31/2015,23:15:00,DANGEROUS DRUGS,MANHATTAN,40.720200,-73.988735
7,12/31/2015,23:15:00,DANGEROUS WEAPONS,BRONX,40.845707,-73.910398
8,12/31/2015,23:15:00,ASSAULT 3 & RELATED OFFENSES,BRONX,40.856711,-73.891900
9,12/31/2015,23:10:00,PETIT LARCENY,MANHATTAN,40.765618,-73.963623
10,12/31/2015,23:05:00,PETIT LARCENY,BRONX,40.822040,-73.891732
11,12/31/2015,23:00:00,PETIT LARCENY,MANHATTAN,40.732828,-73.986063
12,12/31/2015,23:00:00,GRAND LARCENY,MANHATTAN,40.757916,-73.989299
13,12/31/2015,23:00:00,GRAND LARCENY,MANHATTAN,40.757916,-73.989299
14,12/31/2015,23:00:00,FORGERY,BROOKLYN,40.644562,-73.927662
15,12/31/2015,23:00:00,ROBBERY,QUEENS,40.708096,-73.782102
16,12/31/2015,23:00:00,GRAND LARCENY,MANHATTAN,40.755197,-73.968296
17,12/31/2015,23:00:00,OFFENSES AGAINST PUBLIC ADMINI,BRONX,40.857924,-73.891952
18,12/31/2015,23:00:00,ASSAULT 3 & RELATED OFFENSES,BROOKLYN,40.606309,-73.965133
19,12/31/2015,22:55:00,CRIMINAL MISCHIEF & RELATED OF,QUEENS,40.679499,-73.862825
20,12/31/2015,22:53:00,DANGEROUS DRUGS,BROOKLYN,40.655642,-73.959863
21,04/06/2015,12:00:00,RAPE,QUEENS,NaN,NaN
22,12/31/2015,22:50:00,DANGEROUS DRUGS,QUEENS,40.749307,-73.897578
23,12/31/2015,22:50:00,FELONY ASSAULT,BROOKLYN,40.671237,-73.877222
24,12/31/2015,22:45:00,DANGEROUS WEAPONS,BROOKLYN,40.660258,-73.913671
25,12/31/2015,22:45:00,ASSAULT 3 & RELATED OFFENSES,BROOKLYN,40.586060,-73.971743
26,12/31/2015,22:45:00,ASSAULT 3 & RELATED OFFENSES,BROOKLYN,40.633033,-74.021193
27,12/31/2015,22:45:00,DANGEROUS WEAPONS,BROOKLYN,40.669800,-73.892398
28,12/31/2015,22:40:00,DANGEROUS DRUGS,BROOKLYN,40.696494,-73.949431
29,12/31/2015,22:40:00,INTOXICATED & IMPAIRED DRIVING,STATEN ISLAND,40.624475,-74.158203
...,...,...,...,...,...,...
5580005,12/15/2015,15:00:00,OFF. AGNST PUB ORD SENSBLTY &,QUEENS,40.695569,-73.808717
5580006,12/13/2015,23:45:00,BURGLARY,QUEENS,40.722457,-73.808885
5580007,12/13/2015,11:00:00,OFFENSES INVOLVING FRAUD,BRONX,40.832765,-73.855889
5580008,12/13/2015,05:24:00,ARSON,QUEENS,40.654908,-73.851502
5580009,12/11/2015,09:00:00,GRAND LARCENY,BROOKLYN,40.666232,-73.922538
5580010,12/09/2015,12:00:00,HARRASSMENT 2,QUEENS,40.661651,-73.853173
5580011,12/07/2015,16:00:00,HARRASSMENT 2,QUEENS,40.725657,-73.798980
5580012,12/03/2015,18:10:00,GRAND LARCENY,QUEENS,40.783108,-73.779708
5580013,12/01/2015,07:00:00,GRAND LARCENY,BROOKLYN,40.585153,-73.940489
5580014,11/30/2015,00:21:00,ARSON,QUEENS,40.665008,-73.848577
5580015,11/26/2015,17:00:00,HARRASSMENT 2,BRONX,40.862096,-73.824818
5580016,11/26/2015,17:00:00,HARRASSMENT 2,BRONX,40.853241,-73.853654
5580017,11/21/2015,17:40:00,OFF. AGNST PUB ORD SENSBLTY &,MANHATTAN,40.832747,-73.940770
5580018,10/01/2015,16:00:00,SEX CRIMES,QUEENS,NaN,NaN
5580019,09/03/2015,21:22:00,ARSON,QUEENS,40.651416,-73.840882
5580020,07/05/2015,12:00:00,OFF. AGNST PUB ORD SENSBLTY &,QUEENS,40.698159,-73.795085
5580021,07/01/2015,12:00:00,OFF. AGNST PUB ORD SENSBLTY &,STATEN ISLAND,40.565826,-74.130120
5580022,01/01/2015,23:30:00,DANGEROUS DRUGS,BROOKLYN,40.594063,-73.960869
5580023,01/01/2015,22:10:00,HARRASSMENT 2,MANHATTAN,40.711843,-73.999129
5580024,01/01/2015,09:00:00,HARRASSMENT 2,BRONX,40.876713,-73.908501
5580025,01/01/2015,07:40:00,FELONY ASSAULT,BROOKLYN,40.663383,-73.886666
5580026,01/01/2015,06:30:00,HARRASSMENT 2,BROOKLYN,40.693778,-73.907324
5580027,01/01/2015,04:45:00,HARRASSMENT 2,QUEENS,40.755021,-73.803771
5580028,01/01/2015,04:30:00,ASSAULT 3 & RELATED OFFENSES,BRONX,40.827591,-73.895828
5580029,01/01/2015,04:30:00,ROBBERY,QUEENS,40.761002,-73.824423
5580030,01/01/2015,03:50:00,ROBBERY,MANHATTAN,40.825818,-73.948975
5580031,01/01/2015,01:25:00,HARRASSMENT 2,BRONX,40.820315,-73.890825
5580032,01/01/2015,00:30:00,FELONY ASSAULT,QUEENS,40.754199,-73.832963
5580033,06/30/2014,12:00:00,OFF. AGNST PUB ORD SENSBLTY &,BRONX,40.883777,-73.907837
5580034,12/31/2001,16:00:00,BURGLARY,BROOKLYN,40.683617,-73.980416

In [9]:
sel = data[(data["OFNS_DESC"].str.contains("MURDER")) & (data["CMPLNT_FR_DT"].str.contains("2016"))]
sel

,CMPLNT_FR_DT,CMPLNT_FR_TM,OFNS_DESC,BORO_NM,Latitude,Longitude
5101930,12/31/2016,01:05:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.648265,-73.955752
5103068,12/30/2016,00:40:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.837322,-73.910117
5107748,12/26/2016,12:45:00,MURDER & NON-NEGL. MANSLAUGHTER,STATEN ISLAND,40.624237,-74.080756
5107854,12/26/2016,08:14:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.832111,-73.948294
5107855,12/26/2016,08:14:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.832111,-73.948294
5108627,12/25/2016,12:51:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.646328,-73.929804
5114269,12/20/2016,20:24:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.839872,-73.888140
5115641,12/19/2016,18:00:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.806618,-73.936766
5117003,12/18/2016,15:31:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.657587,-73.929054
5118455,12/17/2016,02:20:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.753875,-73.984820
5121311,12/14/2016,18:45:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.809413,-73.944367
5121901,12/01/2016,19:00:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.841691,-73.837040
5122650,12/13/2016,20:45:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.820986,-73.892229
5122770,12/13/2016,18:21:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.679066,-73.915067
5125199,12/11/2016,20:29:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.845985,-73.907463
5125524,12/11/2016,12:22:00,MURDER & NON-NEGL. MANSLAUGHTER,QUEENS,40.669758,-73.802652
5125897,12/11/2016,00:20:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.703807,-73.952859
5128140,12/09/2016,01:50:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.799086,-73.947619
5130465,12/07/2016,15:02:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.638689,-73.916812
5133479,12/05/2016,00:15:00,MURDER & NON-NEGL. MANSLAUGHTER,QUEENS,40.689141,-73.820855
5134115,12/04/2016,21:17:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.626986,-73.914017
5135252,12/03/2016,20:35:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.837684,-73.913257
5139735,11/30/2016,10:24:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.667863,-73.905388
5139932,11/30/2016,02:00:00,MURDER & NON-NEGL. MANSLAUGHTER,QUEENS,40.691197,-73.835461
5139969,11/30/2016,00:43:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.667533,-73.864248
5141731,11/28/2016,23:19:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.849776,-73.937527
5142052,11/28/2016,14:50:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.823424,-73.901583
5143102,11/27/2016,20:30:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.790325,-73.941711
5144185,11/26/2016,21:07:00,MURDER & NON-NEGL. MANSLAUGHTER,STATEN ISLAND,40.621066,-74.084955
5144612,11/26/2016,12:00:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.874181,-73.833872
...,...,...,...,...,...,...
5526474,02/13/2016,03:00:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.817503,-73.941976
5528206,02/11/2016,21:39:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.662693,-73.888307
5529260,02/10/2016,08:54:00,MURDER & NON-NEGL. MANSLAUGHTER,STATEN ISLAND,40.608392,-74.146612
5529781,02/10/2016,08:54:00,MURDER & NON-NEGL. MANSLAUGHTER,STATEN ISLAND,40.608392,-74.146612
5530009,02/10/2016,08:54:00,MURDER & NON-NEGL. MANSLAUGHTER,STATEN ISLAND,40.608392,-74.146612
5532624,02/08/2016,02:21:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.853064,-73.868945
5535538,02/05/2016,21:35:00,MURDER & NON-NEGL. MANSLAUGHTER,QUEENS,40.750332,-73.792131
5535618,02/05/2016,19:15:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.827669,-73.925436
5547233,01/20/2016,16:35:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.706860,-73.948197
5547289,01/27/2016,23:40:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.803394,-73.938145
5547859,01/27/2016,10:50:00,MURDER & NON-NEGL. MANSLAUGHTER,QUEENS,40.596214,-73.764700
5551006,01/24/2016,16:07:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.811393,-73.922315
5551524,01/23/2016,19:54:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.644590,-74.001900
5552699,01/22/2016,09:07:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.684792,-73.878557
5553484,01/21/2016,20:30:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.857923,-73.892896
5554466,01/10/2016,22:06:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.676232,-74.006945
5558574,01/17/2016,21:17:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.576124,-73.999825
5560066,01/16/2016,15:15:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.661080,-73.894823
5560572,01/16/2016,00:40:00,MURDER & NON-NEGL. MANSLAUGHTER,STATEN ISLAND,40.606405,-74.120479
5562837,01/14/2016,14:36:00,MURDER & NON-NEGL. MANSLAUGHTER,STATEN ISLAND,40.548991,-74.230271
5564159,01/13/2016,14:48:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.664760,-73.894042
5566757,01/11/2016,13:29:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.679908,-73.920784
5566910,01/11/2016,09:08:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.681907,-73.894588
5566967,01/11/2016,07:40:00,MURDER & NON-NEGL. MANSLAUGHTER,QUEENS,40.676487,-73.837065
5568266,01/10/2016,03:32:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.683276,-73.930623
5568784,01/09/2016,23:22:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.661562,-73.925946
5573574,01/06/2016,08:21:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.674602,-73.938614
5575826,01/04/2016,11:00:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.873602,-73.845604
5575942,01/04/2016,04:25:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.883928,-73.901324
5578703,01/01/2016,22:55:00,MURDER & NON-NEGL. MANSLAUGHTER,QUEENS,40.687141,-73.856146

In [10]:
sel.to_csv("murders2016.csv", encoding='utf-8', index=False)

In [12]:
sel['CMPLNT_FR_TM'] = pandas.to_datetime(sel['CMPLNT_FR_TM'])
sel

C:\Users\Porter\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,CMPLNT_FR_DT,CMPLNT_FR_TM,OFNS_DESC,BORO_NM,Latitude,Longitude
5101930,12/31/2016,2018-04-02 01:05:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.648265,-73.955752
5103068,12/30/2016,2018-04-02 00:40:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.837322,-73.910117
5107748,12/26/2016,2018-04-02 12:45:00,MURDER & NON-NEGL. MANSLAUGHTER,STATEN ISLAND,40.624237,-74.080756
5107854,12/26/2016,2018-04-02 08:14:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.832111,-73.948294
5107855,12/26/2016,2018-04-02 08:14:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.832111,-73.948294
5108627,12/25/2016,2018-04-02 12:51:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.646328,-73.929804
5114269,12/20/2016,2018-04-02 20:24:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.839872,-73.888140
5115641,12/19/2016,2018-04-02 18:00:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.806618,-73.936766
5117003,12/18/2016,2018-04-02 15:31:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.657587,-73.929054
5118455,12/17/2016,2018-04-02 02:20:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.753875,-73.984820
5121311,12/14/2016,2018-04-02 18:45:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.809413,-73.944367
5121901,12/01/2016,2018-04-02 19:00:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.841691,-73.837040
5122650,12/13/2016,2018-04-02 20:45:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.820986,-73.892229
5122770,12/13/2016,2018-04-02 18:21:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.679066,-73.915067
5125199,12/11/2016,2018-04-02 20:29:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.845985,-73.907463
5125524,12/11/2016,2018-04-02 12:22:00,MURDER & NON-NEGL. MANSLAUGHTER,QUEENS,40.669758,-73.802652
5125897,12/11/2016,2018-04-02 00:20:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.703807,-73.952859
5128140,12/09/2016,2018-04-02 01:50:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.799086,-73.947619
5130465,12/07/2016,2018-04-02 15:02:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.638689,-73.916812
5133479,12/05/2016,2018-04-02 00:15:00,MURDER & NON-NEGL. MANSLAUGHTER,QUEENS,40.689141,-73.820855
5134115,12/04/2016,2018-04-02 21:17:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.626986,-73.914017
5135252,12/03/2016,2018-04-02 20:35:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.837684,-73.913257
5139735,11/30/2016,2018-04-02 10:24:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.667863,-73.905388
5139932,11/30/2016,2018-04-02 02:00:00,MURDER & NON-NEGL. MANSLAUGHTER,QUEENS,40.691197,-73.835461
5139969,11/30/2016,2018-04-02 00:43:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.667533,-73.864248
5141731,11/28/2016,2018-04-02 23:19:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.849776,-73.937527
5142052,11/28/2016,2018-04-02 14:50:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.823424,-73.901583
5143102,11/27/2016,2018-04-02 20:30:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.790325,-73.941711
5144185,11/26/2016,2018-04-02 21:07:00,MURDER & NON-NEGL. MANSLAUGHTER,STATEN ISLAND,40.621066,-74.084955
5144612,11/26/2016,2018-04-02 12:00:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.874181,-73.833872
...,...,...,...,...,...,...
5526474,02/13/2016,2018-04-02 03:00:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.817503,-73.941976
5528206,02/11/2016,2018-04-02 21:39:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.662693,-73.888307
5529260,02/10/2016,2018-04-02 08:54:00,MURDER & NON-NEGL. MANSLAUGHTER,STATEN ISLAND,40.608392,-74.146612
5529781,02/10/2016,2018-04-02 08:54:00,MURDER & NON-NEGL. MANSLAUGHTER,STATEN ISLAND,40.608392,-74.146612
5530009,02/10/2016,2018-04-02 08:54:00,MURDER & NON-NEGL. MANSLAUGHTER,STATEN ISLAND,40.608392,-74.146612
5532624,02/08/2016,2018-04-02 02:21:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.853064,-73.868945
5535538,02/05/2016,2018-04-02 21:35:00,MURDER & NON-NEGL. MANSLAUGHTER,QUEENS,40.750332,-73.792131
5535618,02/05/2016,2018-04-02 19:15:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.827669,-73.925436
5547233,01/20/2016,2018-04-02 16:35:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.706860,-73.948197
5547289,01/27/2016,2018-04-02 23:40:00,MURDER & NON-NEGL. MANSLAUGHTER,MANHATTAN,40.803394,-73.938145
5547859,01/27/2016,2018-04-02 10:50:00,MURDER & NON-NEGL. MANSLAUGHTER,QUEENS,40.596214,-73.764700
5551006,01/24/2016,2018-04-02 16:07:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.811393,-73.922315
5551524,01/23/2016,2018-04-02 19:54:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.644590,-74.001900
5552699,01/22/2016,2018-04-02 09:07:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.684792,-73.878557
5553484,01/21/2016,2018-04-02 20:30:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.857923,-73.892896
5554466,01/10/2016,2018-04-02 22:06:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.676232,-74.006945
5558574,01/17/2016,2018-04-02 21:17:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.576124,-73.999825
5560066,01/16/2016,2018-04-02 15:15:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.661080,-73.894823
5560572,01/16/2016,2018-04-02 00:40:00,MURDER & NON-NEGL. MANSLAUGHTER,STATEN ISLAND,40.606405,-74.120479
5562837,01/14/2016,2018-04-02 14:36:00,MURDER & NON-NEGL. MANSLAUGHTER,STATEN ISLAND,40.548991,-74.230271
5564159,01/13/2016,2018-04-02 14:48:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.664760,-73.894042
5566757,01/11/2016,2018-04-02 13:29:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.679908,-73.920784
5566910,01/11/2016,2018-04-02 09:08:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.681907,-73.894588
5566967,01/11/2016,2018-04-02 07:40:00,MURDER & NON-NEGL. MANSLAUGHTER,QUEENS,40.676487,-73.837065
5568266,01/10/2016,2018-04-02 03:32:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.683276,-73.930623
5568784,01/09/2016,2018-04-02 23:22:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.661562,-73.925946
5573574,01/06/2016,2018-04-02 08:21:00,MURDER & NON-NEGL. MANSLAUGHTER,BROOKLYN,40.674602,-73.938614
5575826,01/04/2016,2018-04-02 11:00:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.873602,-73.845604
5575942,01/04/2016,2018-04-02 04:25:00,MURDER & NON-NEGL. MANSLAUGHTER,BRONX,40.883928,-73.901324
5578703,01/01/2016,2018-04-02 22:55:00,MURDER & NON-NEGL. MANSLAUGHTER,QUEENS,40.687141,-73.856146

In [35]:
sel['BORO_NM']['CMPLNT_FR_TM'].dt.hour.

SyntaxError: invalid syntax (<ipython-input-35-98fced052f2e>, line 1)

In [15]:
hours = sel['CMPLNT_FR_TM'].dt.hour

5101930     1
5103068     0
5107748    12
5107854     8
5107855     8
5108627    12
5114269    20
5115641    18
5117003    15
5118455     2
5121311    18
5121901    19
5122650    20
5122770    18
5125199    20
5125524    12
5125897     0
5128140     1
5130465    15
5133479     0
5134115    21
5135252    20
5139735    10
5139932     2
5139969     0
5141731    23
5142052    14
5143102    20
5144185    21
5144612    12
           ..
5526474     3
5528206    21
5529260     8
5529781     8
5530009     8
5532624     2
5535538    21
5535618    19
5547233    16
5547289    23
5547859    10
5551006    16
5551524    19
5552699     9
5553484    20
5554466    22
5558574    21
5560066    15
5560572     0
5562837    14
5564159    14
5566757    13
5566910     9
5566967     7
5568266     3
5568784    23
5573574     8
5575826    11
5575942     4
5578703    22
Name: CMPLNT_FR_TM, Length: 314, dtype: int64

In [31]:
histo = sel.groupby(hours).count()
histo

,CMPLNT_FR_DT,CMPLNT_FR_TM,OFNS_DESC,BORO_NM,Latitude,Longitude
CMPLNT_FR_TM,,,,,,
0,21,21,21,21,21,21
1,25,25,25,25,25,25
2,20,20,20,20,20,20
3,7,7,7,7,7,7
4,15,15,15,15,15,15
5,10,10,10,10,10,10
6,6,6,6,6,6,6
7,6,6,6,6,6,6
8,7,7,7,7,7,7
9,8,8,8,8,8,8
10,7,7,7,7,7,7
11,3,3,3,3,3,3
12,12,12,12,12,12,12
13,7,7,7,7,7,7
14,10,10,10,10,10,10
15,8,8,8,8,8,8
16,10,10,10,10,10,10
17,11,11,11,11,11,11
18,14,14,14,14,14,14
19,19,19,19,19,19,19
20,17,17,17,17,17,17
21,24,24,24,24,23,23
22,25,25,25,25,25,25
23,22,22,22,22,22,22

In [33]:
forhisto = histo['CMPLNT_FR_DT']

In [34]:
forhisto.to_csv("murderhours.csv", encoding='utf-8')

In [13]:
crimes = sel.groupby(['OFNS_DESC']).count()
crimes

,CMPLNT_FR_DT,CMPLNT_FR_TM,BORO_NM,Latitude,Longitude
OFNS_DESC,,,,,
MURDER & NON-NEGL. MANSLAUGHTER,314,314,314,313,313

In [5]:
sortedCrimes = crimes.sort_values(by=['BORO_NM'], ascending=False)
sortedCrimes.head()

                                RPT_DT  BORO_NM
OFNS_DESC
PETIT LARCENY                    24620    24620
GRAND LARCENY                    16477    16477
HARRASSMENT 2                    13245    13245
ASSAULT 3 & RELATED OFFENSES     10418    10418
CRIMINAL MISCHIEF & RELATED OF   10003    10003

In [79]:
petit = sel[(sel["OFNS_DESC"] == 'PETIT LARCENY')]
grand = sel[(sel["OFNS_DESC"] == 'GRAND LARCENY')]

In [87]:
harass = sel[(sel["OFNS_DESC"] == 'HARRASSMENT 2')]

In [88]:
assault = sel[(sel["OFNS_DESC"] == 'ASSAULT 3 & RELATED OFFENSES')]

In [89]:
criminal = sel[(sel["OFNS_DESC"] == 'CRIMINAL MISCHIEF & RELATED OF')]

In [55]:
petit['RPT_DT'] = pandas.to_datetime(petit['RPT_DT'])

C:\Users\Porter\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [81]:
grand['RPT_DT'] = pandas.to_datetime(grand['RPT_DT'])

C:\Users\Porter\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [90]:
assault['RPT_DT'] = pandas.to_datetime(assault['RPT_DT'])

C:\Users\Porter\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [91]:
harass['RPT_DT'] = pandas.to_datetime(harass['RPT_DT'])

C:\Users\Porter\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [92]:
criminal['RPT_DT'] = pandas.to_datetime(criminal['RPT_DT'])

C:\Users\Porter\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [56]:
petit.head()

            RPT_DT      OFNS_DESC    BORO_NM
5101380 2016-12-31  PETIT LARCENY  MANHATTAN
5101391 2016-12-31  PETIT LARCENY  MANHATTAN
5101458 2016-12-31  PETIT LARCENY  MANHATTAN
5101476 2016-12-31  PETIT LARCENY  MANHATTAN
5101495 2016-12-31  PETIT LARCENY  MANHATTAN

In [82]:
grand.head()

            RPT_DT      OFNS_DESC    BORO_NM
5101244 2016-12-31  GRAND LARCENY  MANHATTAN
5101245 2016-12-31  GRAND LARCENY  MANHATTAN
5101246 2016-12-31  GRAND LARCENY  MANHATTAN
5101255 2016-12-31  GRAND LARCENY  MANHATTAN
5101257 2016-12-31  GRAND LARCENY  MANHATTAN

In [57]:
petit.dtypes

RPT_DT       datetime64[ns]
OFNS_DESC            object
BORO_NM              object
dtype: object

In [77]:
months = petit['RPT_DT'].dt.month

In [93]:
monthsg = grand['RPT_DT'].dt.month

In [96]:
monthsh = harass['RPT_DT'].dt.month

In [97]:
monthsa = assault['RPT_DT'].dt.month

In [98]:
monthsc = criminal['RPT_DT'].dt.month

In [78]:
from collections import Counter
Counter(months)

Counter({1L: 1976,
         2L: 1774,
         3L: 1970,
         4L: 1993,
         5L: 2103,
         6L: 2142,
         7L: 2178,
         8L: 2305,
         9L: 2105,
         10L: 2046,
         11L: 1918,
         12L: 2110})

In [84]:
Counter(monthsg)

Counter({1L: 1328,
         2L: 1131,
         3L: 1392,
         4L: 1286,
         5L: 1365,
         6L: 1438,
         7L: 1396,
         8L: 1465,
         9L: 1338,
         10L: 1418,
         11L: 1384,
         12L: 1536})

In [99]:
Counter(monthsh)

Counter({1L: 1029,
         2L: 920,
         3L: 1131,
         4L: 1109,
         5L: 1224,
         6L: 1178,
         7L: 1079,
         8L: 1235,
         9L: 1116,
         10L: 1142,
         11L: 1064,
         12L: 1018})

In [100]:
Counter(monthsa)

Counter({1L: 761,
         2L: 724,
         3L: 875,
         4L: 885,
         5L: 972,
         6L: 918,
         7L: 959,
         8L: 925,
         9L: 886,
         10L: 910,
         11L: 832,
         12L: 771})

In [101]:
Counter(monthsc)

Counter({1L: 828,
         2L: 745,
         3L: 833,
         4L: 1101,
         5L: 792,
         6L: 981,
         7L: 812,
         8L: 1049,
         9L: 686,
         10L: 893,
         11L: 634,
         12L: 649})